services:
  video-locadora:
    image: clovisgargione/video-locadora
    restart: always
    build: ./
    working_dir: /video-locadora
    environment:
      TZ: America/Sao_Paulo
      DB_IP: banco
    networks:
      msnetwork: {}
    ports:
      - 8082:8085
    command: mvn spring-boot:run
networks:
  msnetwork:
    external: true
