version: '3.9'
services:
  video-locadora:
    image: clovisgargione/video-locadora
    restart: always
    build: ./
    working_dir: /video-locadora
    ports:
      - 80:8081
    command: mvn spring-boot:run